apptainer/sif

- README.md
Because everything is about achievements and badges these days... add CI/ZenHub badges to `README`.
Closes #2
> Add CircleCI/ZenHub badges

- cmd/siftool/info.go
- pkg/sif/fmt.go
- pkg/sif/fmt_test.go
- pkg/sif/lookup.go
Formatting the output of the global header, the descriptor list and the
descriptor info is now done in the sif package for general use instead of
being found in the siftool directly.
> Centralize the formatting routines.

- pkg/sif/sif.go
In f68560db HdrVersion was changed to "02" to account for the
introduction of the "data generic" datatype.
Since the binary layout of the header is not actually changing, only the
value stored in one of the fields, revert HdrVersion to "01". Tools like
singularity and siftool will simply report an unknown datatype if they
run into an image with this type of content. They will still be able to
deal with it (at least at a high level).
> Revert HdrVersion to "01"

- pkg/sif/load.go
- pkg/sif/load_test.go
- pkg/sif/sif.go
The SifReadWriter expresses the operations required to support reading
and writing SIF files. This facilitates testing other code using the sif
package without having to create actual files in the filesystem.
Remove some code redundancy by having LoadContainer call LoadContainerFp
for the common code.
Add a test that exercises the load logic using a mock to validate that
the code is working only thru the SifReadWriter interface.
> Add interface to express operations to perform on SIF file handles

- pkg/sif/log.go
Remove the empty init function and rename the file to log.go, since all
it contains is logging functionality.
> Clean up init.go, rename to log.go

- pkg/sif/fmt.go
- pkg/sif/load.go
- pkg/sif/lookup_test.go
The SIF binary contains C strings (bytes terminated by \000) and there
are not handled consistently when they are output.
Since there's nothing in the actual code that is doing this (other than
having an array initialized to zeroes and not writing anything to the
last element), be a little bit lenient when loading data from the file:
examine the last byte and if it's \000, ignore it.
> Handle C strings more consistently

- .circleci/config.yml
- go.mod
- Update go.mod
- Update .circleci/config.yml
> Set required Go version to 1.11

- .circleci/config.yml
- .markdownlint.json
- CONTRIBUTING.md
- LICENSE.md
- README.md
- pkg/sif/create.go
- pkg/sif/create_test.go
- pkg/sif/fmt.go
- pkg/sif/lookup_test.go
Remove broken ZenHub badge. Add GoDoc and Go Report Card badges. Fix misspelled words. Add `markdownlint` in CI, and fix associated lint.
> Badges and Associated Fixes

- pkg/sif/sif.go
Fixes: #25
Signed-off-by: Michael Bauer <michael@bauer.dev>
> Fix SIF layout comment for godoc formatting

- .circleci/config.yml
- .golangci.yml
- internal/app/siftool/modif.go
Add `go list -mod=readonly` to `cache_go_mod` job to verify `go.mod` is in sync with source code. 
Replace workspace usage with `checkout`/`restore_cache` as recommended on the [CircleCI blog](https://circleci.com/blog/deep-diving-into-circleci-workspaces/).
Advance Go version to 1.12. Use `node:11-slim` (148MB) instead of `node:11` (904MB) for `lint_markdown` job. Update `golangci-lint` to v1.16. Remove `cover.out` artifact, since we aren't using it.
Closes #28
> CI Improvements

- .circleci/config.yml
- scripts/check-vendor
Add scripts/check-vendor to check that the vendor/ directory is
up-to-date wrt go.mod and that the vendor/ directory has not been
modified wrt to what should be there.
Add call to scripts/check-vendor in .circleci/config.yml so that we
verify that vendor/ and/or go.mod has not been updated without updating
the other, too.
> Add script to verify that vendor dir is up-to-date

- .circleci/config.yml
- README.md
Report code coverage metrics. Add badge with code coverage summary. Remove redundant build job (#31). Use default timeout for `go test` in CircleCI config, and remove unnecessary path specifier to `golangci-lint `.
Closes #31, closes #34
> Report Code Coverage Metrics

- .gitignore
- cmd/siftool/siftool.go
This PR improves the `Unknown command:` error when using a unknown command.
Before:
```
$ siftool bar
Unknown command:bar
```
After:
```
$ siftool bar
Unknown command: bar
```
> Slightly improved 'Unknown command:' message

- pkg/sif/lookup.go
If your verifying a container thats corrupted/without a sif header, it will panic. Not any more! This will add a check to ensure the that there is data to return, before returning it.
Related to: https://github.com/sylabs/singularity/pull/3615
<br>
> Return nil if header is corrupted

- pkg/sif/create.go
- pkg/sif/sif.go
This descriptor is intended to store cryptographic messages within sif
files. This includes, but is not limited to clear signed openPGP
messages as well as encrypted RSA-OAEP messages.
Signed-off-by: Ian Kaneshiro <iankane@umich.edu>
Notes for reviewers:
- Message types do not use `iota` for enumeration to allow logical grouping of additional constants over time
- I am thinking about adding an `Extra [remainingExtraSpace]bytes` field to the struct so that for select uses of the descriptor(aka an openPGP signature) we can store fingerprint and entity information in the descriptor portion in a reasonable way and would like feedback on the idea here.
> Add DataCryptoMessage Descriptor

- internal/app/siftool/modif.go
- pkg/sif/fmt.go
- pkg/sif/lookup.go
This adds helpers to deserialize the data stored within the Extra field.
And updates siftool to give useful information about this new type.
Signed-off-by: Ian Kaneshiro <iankane@umich.edu>
> Extend helpers and siftool for CryptoMessage type

- .circleci/config.yml
- README.md
- go.mod
Use Go v1.13 in CI. Update `codecov` Orb to v1.0.5, and `golangci-lint` to v1.18.0.
Remove `cache_go_mod` job, and associated `save_cache`/`restore_cache` steps from all jobs, using the Go module proxy instead. Move existing `scripts/check-vendor` step to a new `check_vendor` job.
Closes #51
> Verify Go 1.13 Compatibility

- pkg/sif/fmt.go
- pkg/sif/fmt_test.go
- pkg/sif/load.go
- pkg/sif/load_test.go
- pkg/sif/lookup_test.go
Update fmt tests so that they actually compare fmt result.
Also trim trailing zero bytes when printing descriptor name (they are not printed but they affect tests and the resulting string).
> Trim zero bytes when format SIF, update tests

- go.mod
This PR re-updates the `go.mod` go version to `1.13`, since we are using
1.13 in Singularity.
> Update go.mod to go1.13

- .circleci/config.yml
- pkg/sif/load.go
Update CI to test with Go 1.14 (while maintaining 1.13 in go.mod, as per the [Go Version Compatibility section of the README](https://github.com/sylabs/sif#go-version-compatibility)).
Update `golangci-lint` to v1.23.7 and, `node` to v12 in CircleCI configuration. Fix a couple of new printf format issues:
```
pkg/sif/load.go:57:20: SA5009: Printf format %s has arg #1 of wrong type [10]byte (staticcheck)
return fmt.Errorf("invalid SIF file: Magic |%s| want |%s|", fimg.Header.Magic, HdrMagic)
^
pkg/sif/load.go:60:20: SA5009: Printf format %s has arg #1 of wrong type [3]byte (staticcheck)
return fmt.Errorf("invalid SIF file: Version %s want <= %s", fimg.Header.Version, HdrVersion)
```
> Go 1.14 and CI Updates

- go.mod
- go.sum
Use stable version of `github.com/spf13/cobra`.
> Bump github.com/spf13/cobra to 1.0.0

- .circleci/config.yml
- pkg/sif/lookup_test.go
Bump `golangci-lint`, and address one piece of lint found by `staticcheck` linter:
```
pkg/sif/lookup_test.go:25:19: SA5011: possible nil pointer dereference (staticcheck)
if string(header.Magic[:9]) != "SIF_MAGIC" {
```
> Bump golangci-lint to 1.27.0

- pkg/sif/load_test.go
- pkg/sif/lookup.go
- pkg/sif/lookup_test.go
- pkg/sif/sif.go
Currently, it is possible to obtain a byte slice of the data associated with an object descriptor using [GetData()](https://godoc.org/github.com/sylabs/sif/pkg/sif#Descriptor.GetData). When the [FileImage](https://godoc.org/github.com/sylabs/sif/pkg/sif#FileImage) is not `mmap`'d, calling `GetData()` to obtain a large data object consumes a significant amount of memory.
Callers may not require the entire data object in memory, and may only be interested in working with a portion of the object. To support this use case in an efficient way, I have added `GetReadSeeker()`, which returns a [`io.ReadSeeker`](https://golang.org/pkg/io/#ReadSeeker), which is a good match for this use case.
I have also fixed a subtle bug in `GetData()`. This function was reading via the [`io.Reader …
> Add GetReadSeeker

- .dependabot/config.yml
- .github/dependabot.yml
Migrate Dependabot configuration to new location and format.
> Migrate to GitHub-native Dependabot

- go.mod
- go.sum
- internal/app/siftool/modif.go
- pkg/integrity/testdata/gen_sifs.go
- pkg/sif/create_test.go
See https://github.com/hpcng/sif/security/advisories/GHSA-33m6-q9v5-62r7
> Update github.com/satori/go.uuid to address CVE-2021-3538

- .github/workflows/goreleaser.yml
The last attempted goreleaser run ended in an error:
```
⨯ release failed after 42.70s error=scm releases: failed to publish artifacts: POST https://api.github.com/repos/hpcng/sif/releases: 403 Resource not accessible by integration []
```
goreleaser/goreleaser#2642 indicates that may have been because of missing "permissions: contents: write" and the [documentation](https://goreleaser.com/ci/actions) also indicates that should be there but it was missing.
> Add write gorelease write permissions

- .github/workflows/ci.yml
- mage.go
- magefile.go
This pulls in the following PR, bringing apptainer/sif up to the level of v2.4.0
- sylabs/sif#179
> Merge sylabs/sif through v2.4.1

- .github/workflows/ci.yml
- .github/workflows/goreleaser.yml
- .goreleaser.yml
This pulls in the following PR, bringing apptainer/sif up to the level of v2.4.2
- sylabs/sif#196
> Merge sylabs/sif through v2.4.2

- .github/dependabot.yml
- README.md
- go.mod
- go.sum
This pulls in the following PRs, bringing apptainer/sif up to the level of v2.7.1
- sylabs/sif#212
- sylabs/sif#215
> Merge sylabs/sif through v2.7.1

- .github/dependabot.yml
Nothing actively supported depends on v1 anymore.
> Remove v1 branch from dependabot

- .github/workflows/goreleaser.yml
This will hopefully fix the error seen during the [first try](https://github.com/apptainer/sif/actions/runs/4409629742/jobs/7726153951) to tag 2.11.0.
> Update goreleaser to go 1.19

- .github/workflows/ci.yml
- cmd/siftool/siftool.go
- pkg/integrity/verify_test.go
- pkg/sif/descriptor_input.go
- pkg/siftool/del.go
- pkg/siftool/dump.go
- pkg/siftool/header.go
- pkg/siftool/info.go
- pkg/siftool/list.go
- pkg/siftool/new.go
- pkg/siftool/setprim.go
This updates to the sylabs/sif v2.15.2 by pulling in
- sylabs/sif#350
- sylabs/sif#352
the latter of which had a PR description of
> `revive` linter now checks for this as of v1.3.7.
> Update to sylabs/sif v2.15.2

- .github/workflows/goreleaser.yml
- go.mod
- go.sum
I don't want to require a golang newer than what's available on EL8 which is golang 1.22.7, so back up sigstore to 1.8.9.
> Back up sigstore to 1.8.9 for go 1.22.7 or older
